spring.application.name=fast_cv

telegram.bot.username=${BOT_USERNAME}
telegram.bot.token=${BOT_TOKEN}

ai.provider=mistral
ai.gemini.api-key=${GEMINI_API_KEY:}
ai.groq.api-key=${GROQ_API_KEY:}
ai.groq.model=meta-llama/llama-4-scout-17b-16e-instruct
ai.mistral.api-key=${MISTRAL_API_KEY:}